### ISSUE TITLE
Track Possible Future Features to be Completed

### ISSUE THREAD

**Issue by glennsvel90** [glennsvel90/food-resources#1]
## TODO

*Features left to work on your spare time*

* [x] Directions to Food Pantries
* [ ] Show where you are located in relation to Food Pantries
* [ ] Button that shows only opened food pantries for the next 4 hours
* [ ] Button that directs one to the nearest opened food pantry opened within 4 hours
